name: A-京618
#活动时间: 2021-5-24至2021-6-20
#活动入口：暂无 [活动地址](https://carnivalcity.m.jd.com/)
on:
  schedule:
    - cron: '0 0-18/6 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./-/C.TXT
        
      - name: '-' 
        run: python3 ./-/Jd618.py
        env:
            Card_telegram: ${{ secrets.Card_telegram }}
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
