name: A-梅赛德斯奔驰

on:
  schedule:
    - cron: '15 2 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./-/C.TXT
        
      - name: '-' 
        run: python3 ./-/XIM.py
        env:
            Card_telegram: ${{ secrets.Card_telegram }}
            XIMEIHD: ${{ secrets.XIMEIHD }}
