name: Lucky_sub

on:
  schedule:
    - cron: '*/30 0-15 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./-/requirements.txt 
        
      - name: '-' 
        run: python3 ./-/Lucky_sub.py 
        env:
            lucky_sub_url: ${{ secrets.lucky_sub_url }}
            lucky_sub_hd: ${{ secrets.lucky_sub_hd }}
            lucky_key_url: ${{ secrets.lucky_key_url }}
            lucky_art_md5: ${{ secrets.lucky_art_md5 }}
