# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#京东极速版签到+赚现金任务
#每日9毛左右，满3，10，50可兑换无门槛红包
#⚠️⚠️⚠️一个号需要运行40分钟左右
#活动时间：长期
#活动入口：京东极速版app-现金签到
#https://gitee.com/lxk0301/jd_scripts/blob/master/jd_speed_sign.js#

name: 东瓜极速版钱到-赚现金任务

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "0 23 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【东瓜极速版钱到-赚现金任务】"
              run: |
                  node Ponysitters_Club_Season.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  SYNCURL: /The.Flash/The.Flash/j00d_s00peed0_sig00n.js
                  SCKEY: ${{ secrets.SCKEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  EFORK: ${{ secrets.EFORK }}
                  GITHUB: ${{ secrets.GITHUB }}
                  HELPURL: ${{ secrets.HELPURL }}
                  
