# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#宠汪汪邀请助力与赛跑助力脚本，感谢github@Zero-S1提供帮助
##更新时间：2021-1-7（宠汪汪助力更新Token的配置正则表达式已改）
#活动入口：京东APP我的-更多工具-宠汪汪
#token时效很短，几个小时就失效了,闲麻烦的放弃就行
#每天拿到token后，可一次性运行完毕即可。
#互助码friendPin是京东用户名，不是昵称（可在京东APP->我的->设置 查看获得）
#token获取途径：
#1、微信搜索'来客有礼'小程序,登陆京东账号，点击底部的'我的'或者'发现'两处地方,即可获取Token，脚本运行提示token失效后，继续按此方法获取即可
#2、或者每天去'来客有礼'小程序->宠汪汪里面，领狗粮->签到领京豆 也可获取Token(此方法每天只能获取一次)
#脚本里面有内置提供的friendPin，如果你没有修改脚本或者BoxJs处填写自己的互助码，会默认给脚本内置的助力。
#https://github.com/nbzongzong/jd_scripts1207

name: 宠x汪x汪邀x请助x力与赛x跑助力

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "15 2 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【宠x汪x汪邀x请助x力与赛x跑助力】"
              run: |
                  node Ponysitters_Club_Season.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  SYNCURL: /The.Flash/The.Flash/j0d_jo0y_r0un.js
                  SCKEY: ${{ secrets.SCKEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  EFORK: ${{ secrets.EFORK }}
                  GITHUB: ${{ secrets.GITHUB }}
