# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#小鸽有礼2
#每天抽奖25豆
#活动入口：https://jingcai-h5.jd.com/#/dialTemplate?activityCode=1354740864131276800
#活动时间：2021年1月28日～2021年2月28日
#更新地址：https://gitee.com/lxk0301/jd_scripts/raw/master/jd_xgyl.js

name: 小鸽有礼

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "35 23 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【小鸽有礼】"
              run: |
                  node Ponysitters_Club_Season.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  SYNCURL: /The.Flash/The.Flash/x0g0yl2.js
                  SCKEY: ${{ secrets.SCKEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  EFORK: ${{ secrets.EFORK }}
                  GITHUB: ${{ secrets.GITHUB }}
